/**
 * Seeds two isolated CA firms with users, clients and a realistic review
 * history, so every screen has something meaningful on first login.
 *
 * Documents are real files from the synthetic datasets suggested by the
 * OBLIQ-in team (see samples/README.md for sources, licenses and which file
 * is used where). No real client or bank data is used.
 *
 * All workflow history is generated by signing in as each demo user and
 * calling the same database functions the API uses, so the audit trail
 * (including its hash chain) is exactly what real usage would produce.
 *
 * Usage:  pnpm seed
 * Needs apps/api/.env with SUPABASE_URL, SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY,
 * and migrations applied. To re-seed: `supabase db reset` (local) or run
 * supabase/reset_demo.sql in the SQL editor (hosted).
 */
import { createHash, randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { config as loadEnv } from 'dotenv';
import {
  createSupabaseAdminClient,
  createSupabaseClient,
  type MemberRole,
  type TypedSupabaseClient,
} from '@obliq/shared';

loadEnv({ path: 'apps/api/.env' });

const { SUPABASE_URL, SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY } = process.env;
if (!SUPABASE_URL || !SUPABASE_ANON_KEY || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error('Missing SUPABASE_URL / SUPABASE_ANON_KEY / SUPABASE_SERVICE_ROLE_KEY in apps/api/.env');
  process.exit(1);
}

export const DEMO_PASSWORD = process.env.DEMO_PASSWORD ?? 'AuditDemo@2026';
const BUCKET = 'audit-documents';
const SAMPLES = path.resolve('samples');

const admin = createSupabaseAdminClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

interface DemoUser {
  key: string;
  email: string;
  fullName: string;
  role: MemberRole;
  firm: 'abc' | 'xyz';
}

const FIRMS = {
  abc: { name: 'ABC & Co.', slug: 'abc-co' },
  xyz: { name: 'XYZ & Co.', slug: 'xyz-co' },
} as const;

const USERS: DemoUser[] = [
  { key: 'rohit', email: 'rohit@abc-co.demo', fullName: 'Rohit Sharma', role: 'staff', firm: 'abc' },
  { key: 'meera', email: 'meera@abc-co.demo', fullName: 'Meera Nair', role: 'staff', firm: 'abc' },
  { key: 'aman', email: 'aman@abc-co.demo', fullName: 'Aman Verma', role: 'reviewer', firm: 'abc' },
  { key: 'priya', email: 'priya@abc-co.demo', fullName: 'Priya Iyer', role: 'partner', firm: 'abc' },
  { key: 'neha', email: 'neha@xyz-co.demo', fullName: 'Neha Kapoor', role: 'staff', firm: 'xyz' },
  { key: 'vikram', email: 'vikram@xyz-co.demo', fullName: 'Vikram Rao', role: 'reviewer', firm: 'xyz' },
];

const MIME: Record<string, string> = {
  '.pdf': 'application/pdf',
  '.csv': 'text/csv',
  '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
};

function check<T>(label: string, result: { data: T; error: { message: string } | null }): NonNullable<T> {
  if (result.error) throw new Error(`${label}: ${result.error.message}`);
  if (result.data === null || result.data === undefined) throw new Error(`${label}: no data returned`);
  return result.data as NonNullable<T>;
}

async function createUser(user: DemoUser): Promise<string> {
  const { data, error } = await admin.auth.admin.createUser({
    email: user.email,
    password: DEMO_PASSWORD,
    email_confirm: true,
    user_metadata: { full_name: user.fullName },
  });
  if (error || !data.user) throw new Error(`create user ${user.email}: ${error?.message}`);
  return data.user.id;
}

async function signIn(email: string): Promise<TypedSupabaseClient> {
  const client = createSupabaseClient(SUPABASE_URL!, SUPABASE_ANON_KEY!);
  const { error } = await client.auth.signInWithPassword({ email, password: DEMO_PASSWORD });
  if (error) throw new Error(`sign in ${email}: ${error.message}`);
  return client;
}

/** Uploads a file from samples/ exactly the way the API does: storage object, then the DB function. */
async function upload(as: TypedSupabaseClient, documentId: string, samplePath: string, note?: string) {
  const body = readFileSync(path.join(SAMPLES, samplePath));
  const fileName = path.basename(samplePath);
  const mimeType = MIME[path.extname(fileName)];
  if (!mimeType) throw new Error(`No MIME type for ${fileName}`);

  const doc = check('load document', await as.from('documents').select('*').eq('id', documentId).single());
  const storagePath = `${doc.firm_id}/${doc.client_id}/${doc.id}/${Date.now()}-${randomUUID().slice(0, 8)}-${fileName}`;
  const stored = await admin.storage.from(BUCKET).upload(storagePath, body, { contentType: mimeType, upsert: false });
  if (stored.error) throw new Error(`storage upload ${fileName}: ${stored.error.message}`);

  check(
    `upload ${fileName}`,
    await as.rpc('record_document_upload', {
      p_document_id: documentId,
      p_storage_path: storagePath,
      p_file_name: fileName,
      p_mime_type: mimeType,
      p_size_bytes: body.length,
      p_sha256: createHash('sha256').update(body).digest('hex'),
      p_response_note: note,
    }),
  );
}

async function rowVersion(as: TypedSupabaseClient, documentId: string): Promise<number> {
  return check('row version', await as.from('documents').select('row_version').eq('id', documentId).single()).row_version;
}

async function startReview(as: TypedSupabaseClient, documentId: string) {
  check('start review', await as.rpc('start_review', { p_document_id: documentId, p_expected_row_version: await rowVersion(as, documentId) }));
}

async function approve(as: TypedSupabaseClient, documentId: string, comment?: string) {
  check(
    'approve',
    await as.rpc('approve_document', {
      p_document_id: documentId,
      p_expected_row_version: await rowVersion(as, documentId),
      p_comment: comment,
    }),
  );
}

async function requestCorrection(as: TypedSupabaseClient, documentId: string, comment: string) {
  check(
    'request correction',
    await as.rpc('request_correction', {
      p_document_id: documentId,
      p_comment: comment,
      p_expected_row_version: await rowVersion(as, documentId),
    }),
  );
}

async function createClientWithDocs(
  as: TypedSupabaseClient,
  name: string,
  details: { pan?: string; gstin?: string },
  documentNames: readonly string[],
) {
  const client = check(
    `create client ${name}`,
    await as.rpc('create_client', { p_name: name, p_pan: details.pan, p_gstin: details.gstin, p_document_names: [...documentNames] }),
  );
  const docs = check('list documents', await as.from('documents').select('id, name').eq('client_id', client.id));
  const byName = Object.fromEntries(docs.map((d) => [d.name, d.id])) as Record<string, string>;
  return { client, docs: byName };
}

async function main() {
  const { data: existing } = await admin.from('firms').select('id').in('slug', [FIRMS.abc.slug, FIRMS.xyz.slug]);
  if (existing && existing.length > 0) {
    console.error(
      'Demo firms already exist. Reset first: `supabase db reset` (local) or run supabase/reset_demo.sql (hosted).',
    );
    process.exit(1);
  }

  console.log('Creating firms…');
  const firms = check('insert firms', await admin.from('firms').insert([FIRMS.abc, FIRMS.xyz]).select('id, slug'));
  const firmId = { abc: firms.find((f) => f.slug === FIRMS.abc.slug)!.id, xyz: firms.find((f) => f.slug === FIRMS.xyz.slug)!.id };

  console.log('Creating users and memberships…');
  const ids: Record<string, string> = {};
  for (const user of USERS) {
    ids[user.key] = await createUser(user);
  }
  check('insert profiles', await admin.from('profiles').insert(USERS.map((u) => ({ id: ids[u.key]!, full_name: u.fullName, email: u.email }))).select('id'));
  check(
    'insert memberships',
    await admin.from('firm_memberships').insert(USERS.map((u) => ({ user_id: ids[u.key]!, firm_id: firmId[u.firm], role: u.role }))).select('user_id'),
  );

  const as: Record<string, TypedSupabaseClient> = {};
  for (const user of USERS) as[user.key] = await signIn(user.email);

  // ---- ABC & Co. — client 1: Trade Links India (AgamiAI bank statement) ----
  console.log('ABC & Co.: Trade Links India…');
  const tradeLinks = await createClientWithDocs(as.priya!, 'Trade Links India', {}, ['Bank Statement', 'GST Return', 'Expense Summary']);
  check('assign rohit', await as.priya!.rpc('assign_staff', { p_client_id: tradeLinks.client.id, p_user_id: ids.rohit! }));

  // The brief's example end to end: incomplete upload → correction → complete upload → approval.
  const bank = tradeLinks.docs['Bank Statement']!;
  await upload(as.rohit!, bank, 'agamiai-indian-bank-statements/trade-links-india_statement_jan-mar-2024_pages-1-2.pdf');
  await startReview(as.aman!, bank);
  await requestCorrection(
    as.aman!,
    bank,
    'Only pages 1–2 of the 6-page statement were uploaded, so page 3 onwards is missing. Please upload the complete Jan–Mar 2024 bank statement.',
  );
  await upload(
    as.rohit!,
    bank,
    'agamiai-indian-bank-statements/trade-links-india_statement_jan-mar-2024.pdf',
    'Uploaded the complete 6-page statement downloaded from the bank.',
  );
  await startReview(as.aman!, bank);
  await approve(
    as.aman!,
    bank,
    'All 6 pages present. Covers 01-Jan-2024 to 31-Mar-2024; opening balance ₹59,131.72, closing balance ₹21,661.82.',
  );

  // ---- ABC & Co. — client 2: Indus Novate Technologies (synthetic-finance-data) ----
  console.log('ABC & Co.: Indus Novate Technologies…');
  const indus = await createClientWithDocs(
    as.aman!,
    'Indus Novate Technologies Pvt Ltd',
    { pan: 'TSZCE1793F', gstin: '29TSZCE1793F7Z7' },
    ['Purchase Register', 'Purchase Invoices', 'Salary Register', 'Vendor Master', 'GST Return'],
  );
  check('assign rohit', await as.aman!.rpc('assign_staff', { p_client_id: indus.client.id, p_user_id: ids.rohit! }));
  check('assign meera', await as.aman!.rpc('assign_staff', { p_client_id: indus.client.id, p_user_id: ids.meera! }));

  // Books register with the dataset's seeded GSTR-2B mismatches → correction required (fix it live in the demo).
  const purchase = indus.docs['Purchase Register']!;
  await upload(as.rohit!, purchase, 'synthetic-finance-data/indus-novate_purchase-register_jun-2026_books.csv');
  await startReview(as.aman!, purchase);
  await requestCorrection(
    as.aman!,
    purchase,
    'The June 2026 books register does not reconcile with GSTR-2B: 6 value mismatches (e.g. CAT/26-27/1017 books ₹7,60,300 vs 2B ₹7,04,000), ' +
      '4 wrong vendor GSTINs (e.g. PIO/26-27/1003), 6 invoices in 2B missing from books (e.g. APE/26-27/1010) and 5 booked invoices not in 2B. ' +
      'Please upload the reconciled register with ITC on the unmatched invoices marked as held.',
  );

  const invoices = indus.docs['Purchase Invoices']!;
  await upload(as.rohit!, invoices, 'synthetic-finance-data/indus-novate_vendor-invoice_INV-202604-012.pdf');
  await startReview(as.aman!, invoices);
  await approve(
    as.aman!,
    invoices,
    'Meridian Facility Management tax invoice INV-202604-012: taxable ₹71,100 + CGST ₹6,399 + SGST ₹6,399 = ₹83,898, agrees with the April purchase register.',
  );

  const salary = indus.docs['Salary Register']!;
  await upload(as.meera!, salary, 'synthetic-finance-data/indus-novate_salary-register_jun-2026.csv', 'June 2026 payroll, 50 employees.');
  await startReview(as.aman!, salary);

  await upload(as.meera!, indus.docs['Vendor Master']!, 'synthetic-finance-data/indus-novate_vendor-master.csv');

  // ---- XYZ & Co. — Pixelcraft Studios (LedgerBridge) ------------------------
  console.log('XYZ & Co.: Pixelcraft Studios…');
  const pixelcraft = await createClientWithDocs(
    as.vikram!,
    'Pixelcraft Studios Pvt Ltd',
    { pan: 'AABCP5678F', gstin: '29AABCP5678F1Z2' },
    ['Bank Statement', 'Payroll Register', 'Monthly MIS Report'],
  );
  check('assign neha', await as.vikram!.rpc('assign_staff', { p_client_id: pixelcraft.client.id, p_user_id: ids.neha! }));

  const pxBank = pixelcraft.docs['Bank Statement']!;
  await upload(as.neha!, pxBank, 'ledgerbridge-pixelcraft-studios/pixelcraft_hdfc-current-account_apr-2025.csv');
  await startReview(as.vikram!, pxBank);
  await approve(as.vikram!, pxBank, 'HDFC current account export for April 2025; opening ₹18,50,000.00, closing ₹18,48,852.30.');

  await upload(as.neha!, pixelcraft.docs['Payroll Register']!, 'ledgerbridge-pixelcraft-studios/pixelcraft_razorpayx-payroll_apr-2025.csv');

  const mis = pixelcraft.docs['Monthly MIS Report']!;
  await upload(as.neha!, mis, 'ledgerbridge-pixelcraft-studios/pixelcraft_monthly-report_apr-2025.xlsx');
  await startReview(as.vikram!, mis);

  for (const [label, session] of [['ABC & Co.', as.aman!], ['XYZ & Co.', as.vikram!]] as const) {
    const verification = check(`verify ${label}`, await session.rpc('verify_audit_chain')) as unknown as { ok: boolean; events: number };
    console.log(`  ${label}: ${verification.events} audit events, chain ${verification.ok ? 'verified ✓' : 'BROKEN ✗'}`);
  }

  console.log('\nDemo accounts (password for all: %s)', DEMO_PASSWORD);
  for (const user of USERS) {
    console.log(`  ${FIRMS[user.firm].name.padEnd(10)} ${user.role.padEnd(9)} ${user.fullName.padEnd(13)} ${user.email}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
