/**
 * Seeds two isolated CA firms with users, clients and a realistic review
 * history, so every screen has something meaningful on first login.
 *
 * All workflow history is generated by signing in as each demo user and
 * calling the same database functions the API uses, so the audit trail
 * (including its hash chain) is exactly what real usage would produce.
 *
 * Usage:  pnpm seed
 * Needs apps/api/.env with SUPABASE_URL, SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY,
 * and migrations applied. To re-seed: `supabase db reset` (local) or run
 * supabase/reset_demo.sql in the SQL editor (hosted).
 */
import { createHash, randomUUID } from 'node:crypto';
import { config as loadEnv } from 'dotenv';
import {
  createSupabaseAdminClient,
  createSupabaseClient,
  DEFAULT_REQUIRED_DOCUMENTS,
  type MemberRole,
  type TypedSupabaseClient,
} from '@obliq/shared';
import { makeCsv, makePdf } from './lib/sample-files.js';

loadEnv({ path: 'apps/api/.env' });

const { SUPABASE_URL, SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY } = process.env;
if (!SUPABASE_URL || !SUPABASE_ANON_KEY || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error('Missing SUPABASE_URL / SUPABASE_ANON_KEY / SUPABASE_SERVICE_ROLE_KEY in apps/api/.env');
  process.exit(1);
}

export const DEMO_PASSWORD = process.env.DEMO_PASSWORD ?? 'AuditDemo@2026';
const BUCKET = 'audit-documents';

const admin = createSupabaseAdminClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

interface DemoUser {
  key: string;
  email: string;
  fullName: string;
  role: MemberRole;
  firm: 'abc' | 'xyz';
}

const FIRMS = {
  abc: { name: 'ABC & Co.', slug: 'abc-co' },
  xyz: { name: 'XYZ & Co.', slug: 'xyz-co' },
} as const;

const USERS: DemoUser[] = [
  { key: 'rohit', email: 'rohit@abc-co.demo', fullName: 'Rohit Sharma', role: 'staff', firm: 'abc' },
  { key: 'meera', email: 'meera@abc-co.demo', fullName: 'Meera Nair', role: 'staff', firm: 'abc' },
  { key: 'aman', email: 'aman@abc-co.demo', fullName: 'Aman Verma', role: 'reviewer', firm: 'abc' },
  { key: 'priya', email: 'priya@abc-co.demo', fullName: 'Priya Iyer', role: 'partner', firm: 'abc' },
  { key: 'neha', email: 'neha@xyz-co.demo', fullName: 'Neha Kapoor', role: 'staff', firm: 'xyz' },
  { key: 'vikram', email: 'vikram@xyz-co.demo', fullName: 'Vikram Rao', role: 'reviewer', firm: 'xyz' },
];

function check<T>(label: string, result: { data: T; error: { message: string } | null }): NonNullable<T> {
  if (result.error) throw new Error(`${label}: ${result.error.message}`);
  if (result.data === null || result.data === undefined) throw new Error(`${label}: no data returned`);
  return result.data as NonNullable<T>;
}

async function createUser(user: DemoUser): Promise<string> {
  const { data, error } = await admin.auth.admin.createUser({
    email: user.email,
    password: DEMO_PASSWORD,
    email_confirm: true,
    user_metadata: { full_name: user.fullName },
  });
  if (error || !data.user) throw new Error(`create user ${user.email}: ${error?.message}`);
  return data.user.id;
}

async function signIn(email: string): Promise<TypedSupabaseClient> {
  const client = createSupabaseClient(SUPABASE_URL!, SUPABASE_ANON_KEY!);
  const { error } = await client.auth.signInWithPassword({ email, password: DEMO_PASSWORD });
  if (error) throw new Error(`sign in ${email}: ${error.message}`);
  return client;
}

type Sessions = Record<string, TypedSupabaseClient>;

async function upload(
  as: TypedSupabaseClient,
  documentId: string,
  fileName: string,
  body: Buffer,
  mimeType: string,
  note?: string,
) {
  const doc = check('load document', await as.from('documents').select('*').eq('id', documentId).single());
  const path = `${doc.firm_id}/${doc.client_id}/${doc.id}/${Date.now()}-${randomUUID().slice(0, 8)}-${fileName}`;
  const stored = await admin.storage.from(BUCKET).upload(path, body, { contentType: mimeType, upsert: false });
  if (stored.error) throw new Error(`storage upload ${fileName}: ${stored.error.message}`);

  check(
    `upload ${fileName}`,
    await as.rpc('record_document_upload', {
      p_document_id: documentId,
      p_storage_path: path,
      p_file_name: fileName,
      p_mime_type: mimeType,
      p_size_bytes: body.length,
      p_sha256: createHash('sha256').update(body).digest('hex'),
      p_response_note: note,
    }),
  );
}

async function rowVersion(as: TypedSupabaseClient, documentId: string): Promise<number> {
  return check('row version', await as.from('documents').select('row_version').eq('id', documentId).single()).row_version;
}

async function startReview(as: TypedSupabaseClient, documentId: string) {
  check('start review', await as.rpc('start_review', { p_document_id: documentId, p_expected_row_version: await rowVersion(as, documentId) }));
}

async function approve(as: TypedSupabaseClient, documentId: string, comment?: string) {
  check(
    'approve',
    await as.rpc('approve_document', {
      p_document_id: documentId,
      p_expected_row_version: await rowVersion(as, documentId),
      p_comment: comment,
    }),
  );
}

async function requestCorrection(as: TypedSupabaseClient, documentId: string, comment: string) {
  check(
    'request correction',
    await as.rpc('request_correction', {
      p_document_id: documentId,
      p_comment: comment,
      p_expected_row_version: await rowVersion(as, documentId),
    }),
  );
}

async function createClientWithDocs(
  as: TypedSupabaseClient,
  name: string,
  details: { pan?: string; gstin?: string },
  documentNames: readonly string[],
) {
  const client = check(
    `create client ${name}`,
    await as
      .rpc('create_client', { p_name: name, p_pan: details.pan, p_gstin: details.gstin, p_document_names: [...documentNames] }),
  );
  const docs = check('list documents', await as.from('documents').select('id, name').eq('client_id', client.id));
  const byName = Object.fromEntries(docs.map((d) => [d.name, d.id])) as Record<string, string>;
  return { client, docs: byName };
}

const bankStatement = (pages: number) =>
  makePdf(
    'HDFC Bank - Current Account Statement',
    Array.from({ length: pages }, (_, i) => [
      'Account: ABC Traders Pvt. Ltd. - XXXX4821',
      'Period: 01-Apr-2025 to 31-Mar-2026',
      `Opening balance (page ${i + 1}): Rs. ${(1245000 + i * 83500).toLocaleString('en-IN')}`,
      'Closing balance carried forward',
    ]),
  );

async function main() {
  const { data: existing } = await admin.from('firms').select('id').in('slug', [FIRMS.abc.slug, FIRMS.xyz.slug]);
  if (existing && existing.length > 0) {
    console.error(
      'Demo firms already exist. Reset first: `supabase db reset` (local) or run supabase/reset_demo.sql (hosted).',
    );
    process.exit(1);
  }

  console.log('Creating firms…');
  const firms = check('insert firms', await admin.from('firms').insert([FIRMS.abc, FIRMS.xyz]).select('id, slug'));
  const firmId = { abc: firms.find((f) => f.slug === FIRMS.abc.slug)!.id, xyz: firms.find((f) => f.slug === FIRMS.xyz.slug)!.id };

  console.log('Creating users and memberships…');
  const ids: Record<string, string> = {};
  for (const user of USERS) {
    ids[user.key] = await createUser(user);
  }
  check('insert profiles', await admin.from('profiles').insert(USERS.map((u) => ({ id: ids[u.key]!, full_name: u.fullName, email: u.email }))).select('id'));
  check(
    'insert memberships',
    await admin.from('firm_memberships').insert(USERS.map((u) => ({ user_id: ids[u.key]!, firm_id: firmId[u.firm], role: u.role }))).select('user_id'),
  );

  const as: Sessions = {};
  for (const user of USERS) as[user.key] = await signIn(user.email);

  // ---- ABC & Co. -----------------------------------------------------------
  console.log('ABC & Co.: clients and review history…');
  const abcTraders = await createClientWithDocs(
    as.priya!,
    'ABC Traders Pvt. Ltd.',
    { pan: 'AABCA1234C', gstin: '27AABCA1234C1Z5' },
    DEFAULT_REQUIRED_DOCUMENTS,
  );
  check('assign rohit', await as.priya!.rpc('assign_staff', { p_client_id: abcTraders.client.id, p_user_id: ids.rohit! }));

  const sharmaFoods = await createClientWithDocs(as.aman!, 'Sharma Foods LLP', { pan: 'AAKFS5678D' }, [
    'Bank Statement',
    'GST Return',
    'Expense Summary',
  ]);
  check('assign meera', await as.aman!.rpc('assign_staff', { p_client_id: sharmaFoods.client.id, p_user_id: ids.meera! }));

  // The brief's example, end to end: upload → review → correction → re-upload → approve.
  const bank = abcTraders.docs['Bank Statement']!;
  await upload(as.rohit!, bank, 'Bank_Statement.pdf', bankStatement(2), 'application/pdf');
  await startReview(as.aman!, bank);
  await requestCorrection(as.aman!, bank, 'Page 3 is missing. Please upload the complete bank statement.');
  await upload(as.rohit!, bank, 'Bank_Statement_complete.pdf', bankStatement(3), 'application/pdf', 'Uploaded the complete 3-page statement from the bank portal.');
  await startReview(as.aman!, bank);
  await approve(as.aman!, bank, 'All 3 pages present; balances reconcile with the ledger.');

  const gst = abcTraders.docs['GST Return']!;
  await upload(as.rohit!, gst, 'GSTR-3B_Mar-2026.pdf', makePdf('GSTR-3B - March 2026', [['GSTIN: 27AABCA1234C1Z5', 'Status: Draft (not filed)']]), 'application/pdf');
  await startReview(as.aman!, gst);
  await requestCorrection(as.aman!, gst, 'This is the draft GSTR-3B. Upload the filed return showing the ARN.');

  const sales = abcTraders.docs['Sales Register']!;
  await upload(
    as.rohit!,
    sales,
    'Sales_Register_FY2025-26.csv',
    makeCsv([
      ['Invoice', 'Date', 'Customer', 'Taxable Value', 'GST'],
      ['INV-1041', '2026-03-02', 'Kiran Retail', 184000, 33120],
      ['INV-1042', '2026-03-09', 'Metro Wholesale', 96500, 17370],
    ]),
    'text/csv',
  );
  await startReview(as.aman!, sales);

  const purchase = abcTraders.docs['Purchase Register']!;
  await upload(
    as.rohit!,
    purchase,
    'Purchase_Register_FY2025-26.csv',
    makeCsv([
      ['Bill', 'Date', 'Supplier', 'Taxable Value', 'GST'],
      ['PB-778', '2026-03-05', 'Shree Cotton Mills', 142000, 7100],
    ]),
    'text/csv',
  );

  await upload(
    as.meera!,
    sharmaFoods.docs['Bank Statement']!,
    'SBI_Statement_FY2025-26.pdf',
    makePdf('SBI - Current Account Statement', [['Account: Sharma Foods LLP - XXXX1190', 'Period: FY 2025-26']]),
    'application/pdf',
  );

  // ---- XYZ & Co. -----------------------------------------------------------
  console.log('XYZ & Co.: clients and review history…');
  const zenith = await createClientWithDocs(
    as.vikram!,
    'Zenith Exports Pvt. Ltd.',
    { pan: 'AAECZ4321K', gstin: '29AAECZ4321K1Z3' },
    DEFAULT_REQUIRED_DOCUMENTS,
  );
  check('assign neha', await as.vikram!.rpc('assign_staff', { p_client_id: zenith.client.id, p_user_id: ids.neha! }));

  const zBank = zenith.docs['Bank Statement']!;
  await upload(as.neha!, zBank, 'ICICI_Statement_FY2025-26.pdf', makePdf('ICICI Bank - Statement', [['Account: Zenith Exports - XXXX7302']]), 'application/pdf');
  await startReview(as.vikram!, zBank);
  await approve(as.vikram!, zBank);
  await upload(
    as.neha!,
    zenith.docs['Sales Register']!,
    'Export_Sales_Register.csv',
    makeCsv([
      ['Invoice', 'Date', 'Buyer', 'FOB Value'],
      ['EXP-2201', '2026-02-18', 'Nordic Home AB', 1250000],
    ]),
    'text/csv',
  );

  for (const [label, session] of [['ABC & Co.', as.aman!], ['XYZ & Co.', as.vikram!]] as const) {
    const verification = check(`verify ${label}`, await session.rpc('verify_audit_chain')) as unknown as { ok: boolean; events: number };
    console.log(`  ${label}: ${verification.events} audit events, chain ${verification.ok ? 'verified ✓' : 'BROKEN ✗'}`);
  }

  console.log('\nDemo accounts (password for all: %s)', DEMO_PASSWORD);
  for (const user of USERS) {
    console.log(`  ${FIRMS[user.firm].name.padEnd(10)} ${user.role.padEnd(9)} ${user.fullName.padEnd(13)} ${user.email}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
